[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

# No [start] block here — the Railway UI Start Command is the single source of truth.
